### ISSUE TITLE
URL has changed again

### ISSUE THREAD

**Issue by Olen** [iVirus/Docker-Geyser#3]
Old URL: https://ci.geysermc.org/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/standalone/build/libs/Geyser-Standalone.jar

New URL:
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/lastSuccessfulBuild/artifact/bootstrap/standalone/build/libs/Geyser-Standalone.jar

**Comment by bartmoorman** [comment]
Thank you. I have updated the URL for Geyser.
